### ISSUE TITLE
node settings do not work

### ISSUE THREAD

**Issue by KanikaNahata** [phylogeography/spread#172] opened 2022-01-31 10:51 UTC
# Problem

The colour or size of the node does not change

Spread link: https://view.spreadviz.org/?output=ddf9ff80-334a-475d-8cdd-901925a32877/af15cdb0-df4a-4aef-86d9-642119a9da5e.json&maps=GH,SN,BF,GW,GN,SL,ML 
<img width="2501" alt="image" src="https://user-images.githubusercontent.com/29096492/151780838-6c0fa1da-4c2b-4302-a0c6-889e90764ffc.png">
<img width="2501" alt="image" src="https://user-images.githubusercontent.com/29096492/151780859-bc14d048-f906-402c-88ca-514f912ecfac.png">

**Comment by fbielejec** [comment] 2022-02-14 15:40
Could not reproduce, please check @jpmonettas, close if not reproducible
![2022-02-14-1644853297_screenshot_3000x1920](https://user-images.githubusercontent.com/468572/153896324-23523d56-ad82-457c-9517-dc348965a6ae.jpg)

**Comment by jpmonettas** [comment] 2022-02-18 13:45
@fbielejec @KanikaNahata I think the confusion here is between nodes and transition src/dst points which are not the same thing. Our current nodes customization changes the look of whatever is of type node on our data. The dots you see in the beginning/end of transitions are just part of transitions and they are always black and with a fixed radius. I can understand the confusion not sure what to do about it.

**Comment by fbielejec** [comment] 2022-03-12 11:34
closing, not a bug

**Closed as completed by fbielejec** 2022-03-12 11:34 UTC
Labels: bug, must-have
